Filter files in the .github directory from the list of changed files

diff --git a/.github/workflows/issue_ops_prettier.yml b/.github/workflows/issue_ops_prettier.yml
--- a/.github/workflows/issue_ops_prettier.yml
+++ b/.github/workflows/issue_ops_prettier.yml
@@ -82,10 +82,11 @@ jobs:
       
             # Get the list of changed files
             CHANGED_FILES=$(git diff --name-only --diff-filter=d "${FIRST_COMMIT}~1" "${LAST_COMMIT}") || { echo "Failed to get the list of changed files"; exit 1; }
+            CHANGED_FILES=$(echo "$CHANGED_FILES" | grep -vE '^\.github/') || { echo "Failed to filter changed files"; exit 1; }
             echo "$CHANGED_FILES"
       
             if [ -n "$CHANGED_FILES" ]; then
-              npx prettier --write --ignore-unknown --end-of-line=auto $CHANGED_FILES '!**/.github/**'
+              npx prettier --write --ignore-unknown --end-of-line=auto $CHANGED_FILES
             else
               echo "No files changed"
             fi
